# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy

class MercedesScraperItem(scrapy.Item):
    make = scrapy.Field()
    model = scrapy.Field()
    trim = scrapy.Field()
    derivative = scrapy.Field()
    derivative_translated = scrapy.Field()
    number_of_doors = scrapy.Field()
    body_type = scrapy.Field()
    power_train = scrapy.Field()
    version_name = scrapy.Field()
    version_name_translated = scrapy.Field()
    manufacturer_code = scrapy.Field()
    configurator_model_year = scrapy.Field()
    uid = scrapy.Field()
    data_date = scrapy.Field()
    conclude_date = scrapy.Field()
    version_availability = scrapy.Field()
    currency = scrapy.Field()
    price = scrapy.Field()
    delivery_costs_msrp = scrapy.Field()
    other_mandatory_costs = scrapy.Field()
    country = scrapy.Field()
    research_date = scrapy.Field()
    start_date = scrapy.Field()
    end_date = scrapy.Field()
    customer_type = scrapy.Field()
    monthly_payment_type = scrapy.Field()
    product_name = scrapy.Field()
    product_description = scrapy.Field()
    monthly_payment_provider_name = scrapy.Field()
    monthly_payment_provider_type = scrapy.Field()
    interest_rate = scrapy.Field()
    rate_type = scrapy.Field()
    contract_duration_months = scrapy.Field()
    yearly_mileage_km = scrapy.Field()
    yearly_mileage_miles = scrapy.Field()
    total_contract_mileage_km = scrapy.Field()
    total_contract_mileage_miles = scrapy.Field()
    deposit_percent = scrapy.Field()
    deposit_msrp = scrapy.Field()
    deposit_base = scrapy.Field()
    num_of_monthly_installments = scrapy.Field()
    first_monthly_installment_amount_msrp = scrapy.Field()
    monthly_installment_amount_msrp = scrapy.Field()
    additional_fees_msrp = scrapy.Field()
    additional_fees_base = scrapy.Field()
    final_payment_type = scrapy.Field()
    final_payment_percent = scrapy.Field()
    final_payment_msrp = scrapy.Field()
    final_payment_base = scrapy.Field()
    data_source = scrapy.Field()
    web_source_url = scrapy.Field()
    oem_web_financial_config_source = scrapy.Field()
    captive_financial_config_source = scrapy.Field()
    non_captive_financial_config_source = scrapy.Field()
    bank_financial_config_source = scrapy.Field()
    sourced_dealer_quote = scrapy.Field()
    jato_internal_source = scrapy.Field()
    other_sources = scrapy.Field()
    vehicle_price_reference = scrapy.Field()
    mandatory_dealer_contribution_percent = scrapy.Field()
    mandatory_dealer_contribution_msrp = scrapy.Field()
    mandatory_dealer_contribution_base = scrapy.Field()
    oem_discount_percent = scrapy.Field()
    oem_discount_msrp = scrapy.Field()
    oem_discount_base = scrapy.Field()
    government_contribution_percent = scrapy.Field()
    government_contribution_msrp = scrapy.Field()
    government_contribution_base = scrapy.Field()
    downpayment_allowance_percent = scrapy.Field()
    downpayment_allowance_msrp = scrapy.Field()
    downpayment_allowance_base = scrapy.Field()
    residual_value_percent = scrapy.Field()
    residual_value_msrp = scrapy.Field()
    residual_value_base = scrapy.Field()
    insurance = scrapy.Field()
    sourced_financed_amount_percent = scrapy.Field()
    sourced_financed_amount_msrp = scrapy.Field()
    sourced_financed_amount_base = scrapy.Field()
    unique_id = scrapy.Field()
    change_status = scrapy.Field()
    updates_column = scrapy.Field()
    backend_data = scrapy.Field()
    vehicle_hash = scrapy.Field()

